name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_16.4.app/Contents/Developer"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Install xcpretty
        run: sudo gem install xcpretty --no-document

      - name: Build (disable code signing)
        run: |
          set -o pipefail
          xcodebuild \
            -project macflare.xcodeproj \
            -scheme macflare \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            build | xcpretty
        env:
          NSUnbufferedIO: "YES"

      - name: Archive logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-logs
          path: ~/Library/Logs/DiagnosticReports/*.crash
